# This workflow will build the package and publish to TestPyPi
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and publish to PyPi

on:
  push:
    tags: 
      - '*'
  workflow_dispatch:

jobs:
  run-workflow-tests:
    name: Run Workflow Tests
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [run-workflow-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install pypa/build
        run: >-
          python3 -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  upload:
    name: Upload release to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: release
      url: https://pypi.org/p/fixate
    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
