# This workflow will build the package and publish to TestPyPi
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and publish to PyPi

on:
  push:
    tags: 
      - '*'
  workflow_dispatch:

jobs:
  run-workflow-tests:
    name: Run Workflow Tests
    uses: ./.github/workflows/test.yml

  build-n-publish:
    name: Build and Publish to PyPi
    runs-on: ubuntu-latest
    needs: [run-workflow-tests]
    environment: release
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install build
      run: |
        python -m pip install --upgrade pip
        python -m pip install build --user
    - name: Build the package
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
